### ISSUE TITLE
no vnsi register if vdr extras installed first

### ISSUE THREAD

**Issue by hoppel118** [nohatssir/openmediavault-vdr-vnsiserver#1]
Hi,

I am on omv 3.0.13 (omvextrasorg 3.0.11, 4.4.0-0.bpo.1-amd64) and would like to use the plugins omv-vdr 3.0.2, omv-vdr-extras 3.0.1 and omv-vdr-vnsiserver 3.0.0.

If I Install omv-vdr, than omv-vdr-eatras and at least omv-vnsiserver I can't see the vnsi-register in the webui of omv. omv-vdr and omv-extras work as expected.

If I install omv-vdr and omv-vnsiserver without omv-extras I see the vnsi register and omv-vdr and omv-vnsiserver work as expected. 

Where is the problem?

Greetings Hoppel

**Comment by ghost** [comment]
It's already fixed in master because I noticed it yesterday. :)

If you wan't to fix it manually until the next version is released (no ETA), you can edit the file `/var/www/openmediavault/js/omv/module/admin/service/vdr/Vnsiserver.js`.

Change the bottom part from:

```
OMV.WorkspaceManager.registerPanel({
    id: 'extras',
    path: '/service/vdr',
    text: _('VNSI'),
    position: 50,
    className: 'OMV.module.admin.service.vdr.Vnsiserver'
});
```

To:

```
OMV.WorkspaceManager.registerPanel({
    id: 'vnsiserver',
    path: '/service/vdr',
    text: _('VNSI'),
    position: 50,
    className: 'OMV.module.admin.service.vdr.Vnsiserver'
});
```

**Comment by hoppel118** [comment]
This doesn't work for me. Edited the file with nano and changed the id from 'extras' to 'vnsiserver'. After that I restarted the vdr service. 

Is there something else to do?

**Comment by ghost** [comment]
Wasn't the issue that it wasn't available in the web interface? Reload the page and make sure the browser cache is cleaned.

**Comment by hoppel118** [comment]
the browser cache was the problem. :)

yeah, great thank you!
