### ISSUE TITLE
vnsiclient of kodi 16.0

### ISSUE THREAD

**Issue by hoppel118** [nohatssir/openmediavault-vdr-vnsiserver#2]
Hi,

I am on omv 3.0.13 (omvextrasorg 3.0.11, 4.4.0-0.bpo.1-amd64) and would like to use the plugins omv-vdr 3.0.2, omv-vdr-extras 3.0.1 and omv-vdr-vnsiserver 3.0.0 (v1.3.1).

As the frontend I use a windows 10 x64 (vnsiclient v1.11.14) machine with kodi 16.0 (with 16.1rc2 I have the same problem).

LiveTV works as expected, but when I try to open "system - tv - client specific - client specific settings" I get the following message. 

**Error: Exception caught on main loop. Exiting**

In the following thread you find a screenshot of the error message:

http://www.vdr-portal.de/board60-linux/board62-software/board95-xbmc-kodi/p1270231-vdr-vdr-plugin-vnsiserver-kodi-kein-tv/#post1270231

Because of this it's not possible to configure the timeshift.

Is this the right place for this issue or shall I post this error directly to fernetmenta?

https://github.com/FernetMenta/vdr-plugin-vnsiserver

Greetings Hoppel

**Comment by ghost** [comment]
The right place is probably at FernetMentas repo. The plugin only compiles VNSI and everything besides that is outside the scope of the plugin.

I've set some extra options in the plugin a long time ago to enable timeshift for VNSI. You can try adding this `vnsiserver.Timeshift = 2` if you want in the meantime. I've forgot what the number 2 does exactly, but it at least enables timeshift. The pro with it is that timeshift will remain enabled even if you change settings in OMV in the future.

**Comment by hoppel118** [comment]
Ok, thanks for your fast answers. Posted it at FernetMentas repo:

https://github.com/FernetMenta/vdr-plugin-vnsiserver/issues/48

I will try `vnsiserver.Timeshift = 2` this tomorrow.

Greetings

**Comment by ghost** [comment]
I see the issue has been resolved. Closing this then! :)

**Comment by hoppel118** [comment]
Yes, fernetmenta is as fast as you in fixing errors. ;) 

But now somebody has to port vnsi to dx11 to make the vdr osd work under windows.

Thanks for your help! Bye
